[tools]
darklua = "seaofvoices/darklua@0.13.1"
lune = "lune-org/lune@0.8.8"
rojo = "rojo-rbx/rojo@7.4.4"
wally = "UpliftGames/wally@0.3.2"
selene = "Kampfkarren/selene@0.27.1"
wally-package-types = "JohnnyMorganz/wally-package-types@1.3.2"
