[package]
name = "paficent/dex-renewed"
version = "0.0.1"
license = "MIT"
authors = ["Paficent"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
private = true
package_dir = "CustomPackages"

[dependencies]
Signal = "lucasmzreal/fastsignal@10.3.1"
Highlighter = "boatbomber/highlighter@0.8.3"
TableUtils = "paficent/tableutils@^1"
