local BrickColorPicker = require(script.components.BrickColorPicker)
local Button = require(script.components.Button)
local Checkbox = require(script.components.Checkbox)
local ClickSystem = require(script.components.ClickSystem)
local ColorPicker = require(script.components.ColorPicker)
local ColorSequenceEditor = require(script.components.ColorSequenceEditor)
local ContextMenu = require(script.components.ContextMenu)
local DropDown = require(script.components.DropDown)
local Frame = require(script.components.Frame)
local IconMap = require(script.components.IconMap)
local Label = require(script.components.Label)
local NumberSequenceEditor = require(script.components.NumberSequenceEditor)
local ScrollBar = require(script.components.ScrollBar)
local Set = require(script.components.Set)
local ViewportTextBox = require(script.components.ViewportTextBox)
local Window = require(script.components.Window)

return {
	components = {
		BrickColorPicker = BrickColorPicker,
		Button = Button,
		Checkbox = Checkbox,
		ClickSystem = ClickSystem,
		ColorPicker = ColorPicker,
		ColorSequenceEditor = ColorSequenceEditor,
		ContextMenu = ContextMenu,
		DropDown = DropDown,
		Frame = Frame,
		IconMap = IconMap,
		Label = Label,
		NumberSequenceEditor = NumberSequenceEditor,
		ScrollBar = ScrollBar,
		Set = Set,
		ViewportTextBox = ViewportTextBox,
		Window = Window,
	},
}
