name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version of this release (e.g. v1.0)'
        required: true
        default: '1.0'
      summary:
        description: 'Summary of this release'
        required: true
        default: 'Initial release'
  push:
    tags: ["v*"]

permissions:
  contents: write

jobs:
  create-release:
    name: Create Release
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create v${{ github.event.inputs.version }} --title "${{ github.event.inputs.version }}" --notes "${{ github.event.inputs.summary }}" --latest

  build-script:
    needs: ["create-release"]
    name: Bundle Dex
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup RoKit
        run: |
          curl -sSf https://raw.githubusercontent.com/rojo-rbx/rokit/main/scripts/install.sh | bash
          echo 'export PATH="$HOME/.rokit/bin:$PATH"' >> $GITHUB_ENV

      - name: Install Neccessary Tools
        run: rokit install

      - name: Install Wally Packages
        run: lune run install

      - name: Bundle
        run: lune run build

      - name: Upload Minified Dex to Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload v${{ github.event.inputs.version }} "build/Dex.luau"

      - name: Upload Minified Dex to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Dex.luau
          path: build/Dex.luau
      
      - name: Upload Dex Model to Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload v${{ github.event.inputs.version }} "build/Dex.rbxm"

      - name: Upload Dex Model to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Dex.rbxm
          path: build/Dex.rbxm